### ISSUE TITLE
Bug: Config value contains typo and is invalid

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#102]
Commit https://github.com/microbiomedata/nmdc-edge/commit/10f3e79b328e9368d707cc4555cb4f003a15a0bd introduced a bug:

https://github.com/microbiomedata/nmdc-edge/blob/10f3e79b328e9368d707cc4555cb4f003a15a0bd/webapp/client/src/config.js#L102

The expression after the `||` is now `"makeLocalUri("` `/` `")"`.

I recommend removing the surrounding double quotes:

```diff
- process.env.REACT_APP_API_URL || "makeLocalUri("/")",
+ process.env.REACT_APP_API_URL || makeLocalUri("/"),
```

**Comment by yxu-lanl** [comment]
When I made the change, I didn't notice that VS Code added the double quotes.

**Comment by yxu-lanl** [comment]
Fixed. Thanks.
