### ISSUE TITLE
Setup VM cluster using Magic Castle

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/nmdc-edge#109]
Create a virtual cluster using CACAO interface that will run NMDC-EDGE workflows using Cromwell. Create head node, worker nodes and networking

**Comment by mflynn-lanl** [comment]
https://docs.jetstream-cloud.org/ui/cacao/deployment_magic_castle/

**Comment by eecavanna** [comment]
Hi @mflynn-lanl, I saw that this has been moved to the "Done" column on the "Jetstream Migration" board. I'll click the "Close" button here on the Issue page. You can reopen it if you consider it not done.
