### ISSUE TITLE
Attach storage using Manila Shares

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/nmdc-edge#110]
Attach shared storage to virtual cluster

**Comment by mflynn-lanl** [comment]
Storage will be available to VM running the website and the virtual cluster

**Comment by eecavanna** [comment]
Hi @mflynn-lanl, I saw that this has been moved to the "Done" column on the "Jetstream Migration" board. I'll click the "Close" button here on the Issue page. I'm not familiar with the issue, itself—you can reopen it if you consider it not done.
