### ISSUE TITLE
Website display results from the workflows in the metagenomic pipeline that succeed even when others fail

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/nmdc-edge#146]
**Is your feature request related to a problem? Please describe.**
Sometimes we have a situation where one or more of the workflows in the metagenomics pipeline fail, but some of the other workflows succeed. For example, ReadsQC succeeds, but MetaAssembly fails. The website currently requires certain files to be present and if any of them are not, it produces an error. 

**Describe the solution you'd like**
I would like for the website to display an error message on the results page for the workflows in the metaG pipeline that failed and display the results for the rest of the workflows that succeeded. 

**Additional context**
This will become especially important when we implement an automated CI/CD solution for syncing NMDC and NMDC-EDGE workflows. We don't want changes to the NMDC workflows to cause the website to break. Whether it is changes to file names, changes to file formats, or removal of required files

**Comment by yxu-lanl** [comment]
This feature was already implemented couple years ago.
