### ISSUE TITLE
Allow NMDC-EDGE to use NMDC ORCiD account

### ISSUE THREAD

**Issue by yxu-lanl** [microbiomedata/nmdc-edge#158]
Add https://nmdc-edge.org/oauth and https://dev.nmdc-edge.org/oauth to the NMDC ORCiD Redirect URIs

**Comment by shreddd** [comment]
I will open up a request with ORCID to add this.

**Comment by shreddd** [comment]
We will also need to add the ORCID brand recommendations into the NMDC edge login, similar to the text and logo we have on the data portal login
![image](https://github.com/microbiomedata/nmdc-edge/assets/143514/8b328eb5-3801-46c4-94d1-c4f863ccc1e8)
"ORCID Account Integration
NMDC requires an ORCID iD to log in. When logged in you have access to features such as downloading files and the ability to create and manage metadata submissions through our Submission Portal.
Click the "ORCID Login" button, to either register for an ORCID iD or, if you already have one, to sign into your ORCID account, then grant permission for NMDC to access your ORCID iD. This allows us to verify your identity and securely connect to your ORCID iD. Additionally, we may use information, such as your name and email, to associate your ORCID record with your NMDC submissions.
Learn more about [what's so special about signing in.](https://orcid.org/blog/2017/02/20/whats-so-special-about-signing)"

**Comment by shreddd** [comment]
Credentials generated and sent to Yan.
