### ISSUE TITLE
Web app depends upon Node.js v16, which is EOL (unsupported)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#20]
According to [the Node.js release schedule](https://github.com/nodejs/release#release-schedule) and [the Node.js blog](https://nodejs.org/en/blog/announcements/nodejs16-eol), Node v16 goes EOL on Monday, September 11, 2023.

According to the installation instructions in this repository (excerpt below), the web app currently depends upon Node v16:

https://github.com/microbiomedata/nmdc-edge/blob/a55cb0f97c5557972562097dc514dd34c8f971b1/installation/README.md?plain=1#L1-L4

Also, according to the GitHub Issue linked below, the installation instructions currently don't work for Node v18. (Note: The GitHub Issue contains a workaround.) 

- https://github.com/microbiomedata/nmdc-edge/issues/15

**Comment by eecavanna** [comment]
I recommend enabling dependabot alerts on this repo (I don't have access to this repo's "Settings" tab).

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/9bf728a9-098a-4846-91e6-9b977d99339f)

**Comment by yxu-lanl** [comment]
<img width="1141" alt="Screenshot 2024-07-01 at 3 14 40 PM" src="https://github.com/microbiomedata/nmdc-edge/assets/38266469/48e51e6f-9d0a-47c7-9973-ed5f41381de8">

**Comment by yxu-lanl** [comment]
@mflynn-lanl Could you upgrade Node.js to V20?

**Comment by eecavanna** [comment]
For reference, the Node version we have been using in the **containerized** version of NMDC EDGE is Node v20.

References:
- [docker-compose.yml](https://github.com/microbiomedata/nmdc-edge/blob/7192ef7451647ba4f16ef53171aad4d590f61367/docker-compose.yml#L8)
- [Dockerfile](https://github.com/microbiomedata/nmdc-edge/blob/7192ef7451647ba4f16ef53171aad4d590f61367/webapp-node20.Dockerfile#L7)
- [docker-compose.prod.yml](https://github.com/microbiomedata/nmdc-edge/blob/7192ef7451647ba4f16ef53171aad4d590f61367/docs/docker-compose.prod.yml#L43)

**Comment by yxu-lanl** [comment]
This is done.
