### ISSUE TITLE
metaT failing at rfam

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/nmdc-edge#208]
**Workflow Name**
metaT

**Project URL**
https://nmdc-edge.org/admin/project?code=dekwfq0w9LzKA52O

**Additional Info**
metaT fails for smaller samples while running `rfam`, including `/expanse/projects/nmdc/edge_app/nmdc-edge/data/test_data/Metatranscriptomics/test_small_interleave.fastq.gz`
I've tried running using the metaT repository but it fails in the same place. The stderr file is empty and there doesn't seem to be anything helpful in the stdout file or in the Cromwell metadata

**Comment by kaijli** [comment]
https://github.com/microbiomedata/metaT/issues/35
