### ISSUE TITLE
Cannot upload files larger than 500 Mebibytes via web UI (Jetstream2)

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/nmdc-edge#218]
File uploads worked for 43Mb and 380MB, but failed for 1.38BG

**Comment by mflynn-lanl** [comment]
Tried to upload 1.38GB file

![Image](https://github.com/microbiomedata/nmdc-edge/assets/19827223/81cb75ef-6586-40f7-9eab-91bcef1ce30a)

**Comment by eecavanna** [comment]
I'm curious what the following show when that error occurs:
- The web browser's JavaScript console
- The logs of the `app` container

**Comment by mflynn-lanl** [comment]
From the javascript console:
```
https://edge-dev.microbiomedata.org/auth-api/user/upload/add
net::ERR_CONNECTION_CLOSED
Promise.then (async)		
(anonymous)	@	util.js:32
u	@	util.js:30
(anonymous)	@	Uploadfiles.js:108
c	@	Uploadfiles.js:100
onSubmit	@	Uploadfiles.js:98
```
There isn't anything in the log files related to this

**Comment by eecavanna** [comment]
Thanks for sharing the console snippet and note about the logs.

I checked the logs early Tuesday morning (PT) and here are the lines I saw with that path in them:

```clean
// $ docker compose logs app | grep '/auth-api/user/upload/add'

exouser-app-1  | 2024-06-30 18:40:39 debug: 	/auth-api/user/upload/add: {"name":"Ecoli_10x-int.fastq.gz","type":"fastq.gz","size":"43000093"}
exouser-app-1  | 2024-06-30 19:51:27 debug: 	/auth-api/user/upload/add: {"name":"SRR7877884-int-0.1.fastq.gz","type":"fastq.gz","size":"385094750"}
exouser-app-1  | 2024-07-01 15:10:41 debug: 	/auth-api/user/upload/add: {"name":"SRR7877884-int-0.1.fastq.gz","type":"fastq.gz","size":"385094750"}
exouser-app-1  | 2024-07-01 23:08:35 debug: 	/auth-api/user/upload/add: {"name":"Ecoli_10x-int.fastq.gz","type":"fastq.gz","size":"43000093"}
```

- 43000093 Bytes is ~ 43 MB
- 385094750 Bytes is ~ 385 MB
- I don't see any other files sizes (e.g. 1.38 GB) among those log lines

One more thing I'm interested in seeing is the "Network" tab of the web browser's DevTools, when the upload is happening. I want to see what stage the request gets to.

**Comment by eecavanna** [comment]
I see that the default value of the `config.FILE_UPLOADS.MAX_FILE_SIZE_BYTES` config variable is 10 GB; so, I don't think it's an issue of that being too low.

https://github.com/microbiomedata/nmdc-edge/blob/7bcee5bff833575c6a84eefc6132b7efd4c11c4e/webapp/server/config.js#L148

**Comment by eecavanna** [comment]
I reproduced the symptom with a 1 GB file.

I created the file by running (on my laptop):

```shell
head -c 1000000000 /dev/urandom > my-fake-1-gigabyte.fastq.gz
```

When I tried uploading it to the web app, the upload failed after 2 minutes.

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/e3ab4e09-d056-4d3f-b7af-9624efa62e99)

**Note:** I confirmed that I could successfully upload a 1 MB file (also generated from `/dev/urandom`). I may try some files at intermediate sizes (e.g. 750 MB).

**Comment by eecavanna** [comment]
I see this [post](https://caddy.community/t/increase-request-limit/21816/2) in the Caddy community forum. Note that this is not in response to anything I've posted—it's an existing forum thread from 2023.

<img width="777" alt="image" src="https://github.com/microbiomedata/nmdc-edge/assets/134325062/b3166710-40a7-40e6-9767-8dd9c61c7732">

**Comment by eecavanna** [comment]
I confirmed I could upload a 500 MB file. Here's what the "Network" tab shows in that situation.

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/db0c5b0b-ed7b-44f3-978d-0c47c5ad595c)

**Comment by eecavanna** [comment]
Uploading a 990 MB file fails after 2 minutes.

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/7ccf6aaf-7c03-4ca2-847a-0ae8dfc29add)

**Comment by eecavanna** [comment]
Uploading a 750 MB file fails after 2.2 minutes.

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/3f2a4499-9a82-40e3-b9ab-fed55ac99bc4)

**Comment by eecavanna** [comment]
Uploading a 600 MB file fails after 2.2 minutes.

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/0f26f0f8-c0d7-489e-b415-6c8311501f67)

**Comment by eecavanna** [comment]
I confirmed I could upload a 513 MB file.

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/3b8315f4-45d9-4f32-997b-adce7b1ad453)
> Note: The green notification auto-hid itself before I managed to take a screenshot.

**Comment by eecavanna** [comment]
I think the limit is somewhere between 512 Megabytes and 600 Megabytes.

512 Megabytes = 500,000,000 Bytes

512 Mebibytes (MEga-BInary-Bytes) = 536,870,912

I will test the latter.

**Comment by eecavanna** [comment]
Uploading a 513 Mebibyte file fails after 2.1 minutes.

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/e5011856-b8bf-427d-99eb-3d8df3034f4f)

**Comment by eecavanna** [comment]
Uploading a 511 Mebibyte file fails after 2.2 minutes.

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/c3768f1a-53f3-4092-b131-f67156293ddd)

**Comment by eecavanna** [comment]
Based upon the past two attempts, I no longer suspect the limit is 512 Mebibytes. It could be 500 Mebibytes, which is 524,288,000 Bytes.

**Comment by eecavanna** [comment]
I confirmed I could upload a 499 Mebibyte file. It took 3.5 minutes.

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/6ed25a10-cbbe-4b21-a1ca-9274199b9efb)

**Comment by eecavanna** [comment]
Uploading a 501 Mebibyte file fails in 2.1 minutes.

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/cc51daef-aff3-47b9-97c3-aa6675d180b1)

Bingo! I think the limit is 500 Mebibytes.

**Comment by eecavanna** [comment]
@mflynn-lanl, the max upload size seems to me to be 500 Mebibytes (which is `524288000` Bytes). I consider that to be a "clue" as to what is imposing the limit. I'll keep an eye out for that value as I continue looking for a culprit.

**Comment by eecavanna** [comment]
We could turn off Cloudflare's "Proxy" feature for this domain, but we'd lose out on the benefits of having it turned on; e.g. automatic SSL certificate provisioning and renewal, protection against certain types of network attacks.

**Comment by eecavanna** [comment]
I turned off Cloudflare's "Proxy" feature for the `edge-dev` subdomain. Then, I confirmed I could upload a 501 Mebibyte file successfully (previously, uploading the same file failed).

**Comment by eecavanna** [comment]
A 1 Gigabyte upload still fails; but... we get more information now.

Instead of just showing "Stalled" and "Initial connection (2.0 minutes)" (as [happened](https://github.com/microbiomedata/nmdc-edge/issues/218#issuecomment-2204513720) when Cloudflare was proxying requests); now, the "Network" tab (of my web browser's DevTools) shows that the request timed out (the HTTP response was `HTTP 408 Request Timeout`).

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/7817139b-545c-4eb7-bbe2-74d7634ce983)

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/d3277718-c358-4635-a105-c8de8e25bcc7)

Next step: Find out what is configured to time out after 5 minutes. I think it's either Caddy or something in the web app (now that Cloudflare is out of the equation, other than for DNS resolution).

**Comment by eecavanna** [comment]
From Caddy's [docs](https://caddyserver.com/docs/caddyfile/options#timeouts):

> `timeouts`
> - `idle` is a [duration value](https://caddyserver.com/docs/conventions#durations) that sets the maximum time to wait for the next request when keep-alives are enabled. **Defaults to 5 minutes** to help avoid resource exhaustion.

**Comment by eecavanna** [comment]
At the time the upload fails, I see these lines in the Caddy log:

```
exouser-caddy-1  | {"level":"error","ts":1720044809.4940464,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"read tcp 192.168.0.2:60702->192.168.0.4:5000: read: connection reset by peer"}
exouser-caddy-1  | {"level":"error","ts":1720044809.4941583,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"app:5000","duration":309.991915694,"request":{"remote_ip":"76.158.124.194","remote_port":"61441","client_ip":"76.158.124.194","proto":"HTTP/2.0","method":"POST","host":"edge-dev.microbiomedata.org","uri":"/auth-api/user/upload/add","headers":{"Priority":["u=1, i"],"Accept-Language":["en-US,en;q=0.9"],"X-Forwarded-Proto":["https"],"Cookie":[],"Accept":["application/json, text/plain, */*"],"Sec-Ch-Ua-Mobile":["?0"],"Content-Length":["1000000531"],"Cache-Control":["no-cache"],"Sec-Ch-Ua":["\"Brave\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\""],"Referer":["https://edge-dev.microbiomedata.org/user/files"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Dest":["empty"],"Sec-Gpc":["1"],"Sec-Fetch-Site":["same-origin"],"Pragma":["no-cache"],"X-Forwarded-Host":["edge-dev.microbiomedata.org"],"Authorization":[],"Accept-Encoding":["gzip, deflate, br, zstd"],"X-Forwarded-For":["76.158.124.194"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"],"Origin":["https://edge-dev.microbiomedata.org"],"Content-Type":["multipart/form-data; boundary=----WebKitFormBoundaryzCs3N3kdNMcOfvdy"],"Sec-Ch-Ua-Platform":["\"macOS\""]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"edge-dev.microbiomedata.org"}},"error":"reading: read tcp 192.168.0.2:60702->192.168.0.4:5000: read: connection reset by peer"}
exouser-caddy-1  | {"level":"error","ts":1720044809.4942892,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"__REDACTED__","remote_port":"61441","client_ip":"__REDACTED__","proto":"HTTP/2.0","method":"POST","host":"edge-dev.microbiomedata.org","uri":"/auth-api/user/upload/add","headers":{"Content-Length":["1000000531"],"Authorization":[],"Referer":["https://edge-dev.microbiomedata.org/user/files"],"Accept-Language":["en-US,en;q=0.9"],"Sec-Fetch-Mode":["cors"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Accept":["application/json, text/plain, */*"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"],"Origin":["https://edge-dev.microbiomedata.org"],"Sec-Fetch-Dest":["empty"],"Cookie":[],"Sec-Fetch-Site":["same-origin"],"Pragma":["no-cache"],"Cache-Control":["no-cache"],"Sec-Ch-Ua":["\"Brave\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\""],"Content-Type":["multipart/form-data; boundary=----WebKitFormBoundaryzCs3N3kdNMcOfvdy"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Sec-Gpc":["1"],"Priority":["u=1, i"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"edge-dev.microbiomedata.org"}},"bytes_read":878797125,"user_id":"","duration":0,"size":0,"status":408,"resp_headers":{"Server":["Caddy"],"Alt-Svc":["h3=\":443\"; ma=2592000"]}}
```

Highlights (from those lines):

- `"msg": "aborting with incomplete response","upstream":"app:5000","duration":309.991915694`
- `"Content-Length":["1000000531"]`
- `"error":"reading: read tcp 192.168.0.2:60702->192.168.0.4:5000: read: connection reset by peer"`
- `"bytes_read":878797125`

**Comment by eecavanna** [comment]
At the time the upload fails (i.e. approximately 5 minutes after starting the upload), I see these lines in the `caddy` container's log:

```
exouser-caddy-1  | {"level":"error","ts":1720044809.4940464,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"read tcp 192.168.0.2:60702->192.168.0.4:5000: read: connection reset by peer"}
exouser-caddy-1  | {"level":"error","ts":1720044809.4941583,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"app:5000","duration":309.991915694,"request":{"remote_ip":"__REDACTED__","remote_port":"61441","client_ip":"__REDACTED__","proto":"HTTP/2.0","method":"POST","host":"edge-dev.microbiomedata.org","uri":"/auth-api/user/upload/add","headers":{"Priority":["u=1, i"],"Accept-Language":["en-US,en;q=0.9"],"X-Forwarded-Proto":["https"],"Cookie":[],"Accept":["application/json, text/plain, */*"],"Sec-Ch-Ua-Mobile":["?0"],"Content-Length":["1000000531"],"Cache-Control":["no-cache"],"Sec-Ch-Ua":["\"Brave\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\""],"Referer":["https://edge-dev.microbiomedata.org/user/files"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Dest":["empty"],"Sec-Gpc":["1"],"Sec-Fetch-Site":["same-origin"],"Pragma":["no-cache"],"X-Forwarded-Host":["edge-dev.microbiomedata.org"],"Authorization":[],"Accept-Encoding":["gzip, deflate, br, zstd"],"X-Forwarded-For":["__REDACTED__"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"],"Origin":["https://edge-dev.microbiomedata.org"],"Content-Type":["multipart/form-data; boundary=----WebKitFormBoundaryzCs3N3kdNMcOfvdy"],"Sec-Ch-Ua-Platform":["\"macOS\""]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"edge-dev.microbiomedata.org"}},"error":"reading: read tcp 192.168.0.2:60702->192.168.0.4:5000: read: connection reset by peer"}
exouser-caddy-1  | {"level":"error","ts":1720044809.4942892,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"__REDACTED__","remote_port":"61441","client_ip":"__REDACTED__","proto":"HTTP/2.0","method":"POST","host":"edge-dev.microbiomedata.org","uri":"/auth-api/user/upload/add","headers":{"Content-Length":["1000000531"],"Authorization":[],"Referer":["https://edge-dev.microbiomedata.org/user/files"],"Accept-Language":["en-US,en;q=0.9"],"Sec-Fetch-Mode":["cors"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Accept":["application/json, text/plain, */*"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"],"Origin":["https://edge-dev.microbiomedata.org"],"Sec-Fetch-Dest":["empty"],"Cookie":[],"Sec-Fetch-Site":["same-origin"],"Pragma":["no-cache"],"Cache-Control":["no-cache"],"Sec-Ch-Ua":["\"Brave\";v=\"125\", \"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\""],"Content-Type":["multipart/form-data; boundary=----WebKitFormBoundaryzCs3N3kdNMcOfvdy"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Sec-Gpc":["1"],"Priority":["u=1, i"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"edge-dev.microbiomedata.org"}},"bytes_read":878797125,"user_id":"","duration":0,"size":0,"status":408,"resp_headers":{"Server":["Caddy"],"Alt-Svc":["h3=\":443\"; ma=2592000"]}}
```

Highlights (from those lines):

- `"msg": "aborting with incomplete response","upstream":"app:5000","duration":309.991915694`
- `"Content-Length":["1000000531"]`
- `"error":"reading: read tcp 192.168.0.2:60702->192.168.0.4:5000: read: connection reset by peer"`
- `"bytes_read":878797125`

The timestamp `1720044809.4940464` translates to `Wednesday, July 3, 2024 10:13:29.494 PM (GMT)` or `Wednesday, July 3, 2024 3:13:29.494 PM GMT-07:00 DST` ([reference](https://www.epochconverter.com/timezones?q=1720044809.4940464)).

---

On a side note, I also see this in the `app` container's log, but the timestamps seem to be 1 minute off from the ones above:

```
exouser-app-1    | 2024-07-03 22:14:29 debug: 	/auth-api/user/upload/add: {}
exouser-app-1    | 2024-07-03 22:14:29 error: 	[object Object]
```

**Comment by eecavanna** [comment]
The original issue has been fixed—users can now upload files larger than 500 MiB.

The new issue is that uploads taking longer than 5 minutes fail. I opened a new ticket about that, here: https://github.com/microbiomedata/nmdc-edge/issues/232
