### ISSUE TITLE
Convert WDL files to v1.0

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/nmdc-edge#262]
**Is your feature request related to a problem? Please describe.**
We need to switch to v1.0 for our WDL's to match what's used for the NMDC

**Describe the solution you'd like**
Convert each of the nmdc-edge WDL's to v1.0

**Additional context**
Both the individual WDL's need to be converted as well as the metaG pipeline template file `metagenome_pipeline_wdl.tmpl`

This is related to a FY24 Q4 milestone. Target due date for this task is end of August, quarter ends end of Sept.

**Comment by aclum** [comment]
Adding to this sprint since @vlilanl is working on it.

**Comment by ssarrafan** [comment]
@vlilanl said this is in progress but won't be done today. Moving to next sprint.  FYI @aclum

**Comment by ssarrafan** [comment]
@vlilanl @aclum @mflynn-lanl what's the status of this. Hasn't been updated for 2 weeks.
