### ISSUE TITLE
email link for failed projects

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/nmdc-edge#316]
**Is your feature request related to a problem? Please describe.**
When a project fails, I would like a link to be shown on the project page so the user can send me an email asking for help if they like. While there is an email listed on the home page, users don't see it and send emails to leadership instead

**Describe the solution you'd like**
To display the help email address nmdc-edge@lanl.gov for failed projects. I would also like the link to disappear if the project has been re-run successfully

**Comment by yxu-lanl** [comment]
Is this ok?
<img width="689" alt="Screenshot 2024-11-12 at 2 23 43 PM" src="https://github.com/user-attachments/assets/48ffc1d1-153c-4178-8b25-e18120729c6c">

**Comment by mflynn-lanl** [comment]
That looks good, but can you include text telling the user to include their orcid email and the project name (or the project code which would be best!)
________________________________
From: yxu-lanl ***@***.***>
Sent: Tuesday, November 12, 2024 2:26 PM
To: microbiomedata/nmdc-edge ***@***.***>
Cc: Flynn, Mark C ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/nmdc-edge] email link for failed projects (Issue #316)


Is this ok?
Screenshot.2024-11-12.at.2.23.43.PM.png (view on web)<https://urldefense.com/v3/__https://github.com/user-attachments/assets/48ffc1d1-153c-4178-8b25-e18120729c6c__;!!Bt8fGhp8LhKGRg!HIFj4gY-QvFfh5WENo2mioNmbEosqBRMb9AMI_jwtdqhPNhVKdRB-XY8q57xHmJrcL3UMOGNkejqLxomkzMJ29u6$>
