### ISSUE TITLE
Document some environment variables used by web client

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#35]
Hi @yxu-lanl, while reviewing the environment variables used by the web app, I noticed the web app client references some environment variables that aren't defined in the `client-env-prod` file or the `client-end-dev` file. 

Those environment variables are:

- `process.env.REACT_APP_SOCIAL_SECRET` (referenced by `ORCIDLogin.js`)
- `process.env.REACT_APP_DISTRIBUTION_NOTE` (referenced by `Login.js`)
- `process.env.REACT_APP_FILEUPLOAD` (referenced by `TheHeaderDropdown.js`)

Will you document those environment variables (e.g. in what situations someone might define them)? Are they obsolete?

**Comment by yxu-lanl** [comment]
process.env.REACT_APP_SOCIAL_SECRET (referenced by ORCIDLogin.js): a random string, part of ORCiD user password in local DB
process.env.REACT_APP_DISTRIBUTION_NOTE (referenced by Login.js): Used by our other project, we remove it
process.env.REACT_APP_FILEUPLOAD (referenced by TheHeaderDropdown.js): Used by our other project, we remove it

**Comment by eecavanna** [comment]
Thanks, @yxu-lanl.

Here are the specific lines where the latter two are referenced

- `process.env.REACT_APP_DISTRIBUTION_NOTE`:

    https://github.com/microbiomedata/nmdc-edge/blob/e7b48dd6eb2a74e6156a9cd80c6c54510daa70cd/webapp/client/src/common/UM/User/Login.js#L167-L172

- `process.env.REACT_APP_FILEUPLOAD`:

    https://github.com/microbiomedata/nmdc-edge/blob/e7b48dd6eb2a74e6156a9cd80c6c54510daa70cd/webapp/client/src/containers/TheHeaderDropdown.js#L43-L56

**Comment by eecavanna** [comment]
I'm confused about `process.env.REACT_APP_SOCIAL_SECRET`:

In production, is this something the person that deploys the web app would create in the shell environment before building the React app (e.g. `$ export REACT_APP_SOCIAL_SECRET=foo123`)?

I am wondering why the variable is not defined alongside the other environment variables (i.e. in one of the config file templates, with a `<replace me>` value). 

> a random string, part of ORCiD user password in local DB

By "local DB", do you mean the Mongo database used by the web app server, or the web browser's LocalStorage/SessionStorage?

**Comment by eecavanna** [comment]
I'm also wondering whether it would be sufficient to refrain from storing passwords anywhere and, instead, only store the tokens that were obtained using those passwords.

**Comment by yxu-lanl** [comment]
> I'm confused about `process.env.REACT_APP_SOCIAL_SECRET`:
> 
> In production, is this something the person that deploys the web app would create in the shell environment before building the React app (e.g. `$ export REACT_APP_SOCIAL_SECRET=foo123`)?
> 
> I am wondering why the variable is not defined alongside the other environment variables (i.e. in one of the config file templates, with a `<replace me>` value).
> 
> > a random string, part of ORCiD user password in local DB
> 
> By "local DB", do you mean the Mongo database used by the web app server, or the web browser's LocalStorage/SessionStorage?

In MongoDB. The NMDC-EDGE also supports the email/password login. So, using the random string to prevent users logging in with <id>@orcid.org/password. I think we can generate the random string inside the js.

**Comment by eecavanna** [comment]
Thanks, @yxu-lanl. I'm still confused about the purpose of `REACT_APP_SOCIAL_SECRET`. I will send you a message on Slack about it.

**Comment by eecavanna** [comment]
Thanks for explaining it to me. I am in favor of moving the definition and usage of `REACT_APP_SOCIAL_SECRET` to the server side, given its role.

**Comment by eecavanna** [comment]
Resolved via #36
