### ISSUE TITLE
Readbased Analysis Centrifuge error

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/nmdc-edge#51]
**Workflow Name**
Readbased Analysis

**Project URL**

**Additional Info**
`/expanse/projects/nmdc/cromwell/cromwell-executions/main_workflow/669320c0-2d86-44d6-a9c8-6fba4d292db2/call-ReadbasedAnalysis/ReadbasedAnalysis.ReadbasedAnalysis/323c5fc2-c514-4eaa-bfda-482748126934/call-profilerCentrifuge/execution/stderr`:
`'(ERR): mkfifo(/tmp/37.unp) failed.\nExiting now ...`

**Comment by chienchi** [comment]
I rerun it and finished without error. It could be something to do with high usage, or bandwidth that make tmp/ folder not available according to this [issue](https://github.com/bcbio/bcbio-nextgen/issues/2074).  @poeli Have you seen this error before?

**Comment by mflynn-lanl** [comment]
workflow was re-run with error so I'm closing this
