### ISSUE TITLE
Genomad output table reformatting

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/nmdc-edge#54]
**Is your feature request related to a problem? Please describe.**
User had issues loading results page for Genomad run, potentially due to large output file format. 

**Describe the solution you'd like**

Reformat summary table format to limited number of rows/top hits, then provide the whole table in downloadable format for offline viewing. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ljohnson09** [comment]
Both metaG full workflow output and w/ standalone viruses and plasmids workflow

**Comment by yxu-lanl** [comment]
Will use a pagination data table to solve the loading issue.

**Comment by yxu-lanl** [comment]
https://github.com/microbiomedata/nmdc-edge/pull/263
