### ISSUE TITLE
Implement new data visualizations

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/nmdc-edge#66]
**Is your feature request related to a problem? Please describe.**

Requests for more visualizations

**Describe the solution you'd like**

Paul, Chienchi consultation for LANL EDGE visualizations; Pie chart of kegg annotations, IGV/Jbrowse for genome assemblies, @ljohnson09 to ask user for specific MGR visualizations they wanted, ordered in priority; Can add contig length, annotation plot, metabolic maps (licensing w/ kegg?), jbrowse (less useful for many contigs, low priority), heatmap for taxonomy classifiers. Investigate how easy to port to NMDC EDGE; do in a test environment and discuss w/ Emiley 

**Describe alternatives you've considered**

**Additional context**

**Comment by ljohnson09** [comment]
Additional workflow comment: MAG output - discuss if we can add a new output for annotations on a per-MAG basis

**Comment by ljohnson09** [comment]
![image1](https://github.com/microbiomedata/nmdc-edge/assets/126267639/ee511366-9cae-40bd-bf36-a09c787c2e31)
![image2](https://github.com/microbiomedata/nmdc-edge/assets/126267639/7be102e7-d2d6-4102-a943-afe8b0de1137)
Some examples of MAG annotation requested from a user^

**Comment by chienchi** [comment]
Tool could generate similar headmaps for MAGs.
https://github.com/cruizperez/MicrobeAnnotator?tab=readme-ov-file#license 
`ko_mapper.py.`
