### ISSUE TITLE
MetaG - Genomad linkages

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/nmdc-edge#71]
**Is your feature request related to a problem? Please describe.**

Users wanted connection between metaG and genomad workflows

**Describe the solution you'd like**

Under team discussion for feasibility, how to build genomad into metaG. 

**Describe alternatives you've considered**

**Additional context**

**Comment by mflynn-lanl** [comment]
A branch with all of the changes necessary to run Genomad as a part of the metaG pipeline has been made. https://github.com/microbiomedata/nmdc-edge/tree/add-genomad-to-metaG
@yxu-lanl Can you make the changes on the frontend?
