### ISSUE TITLE
Client env file templates have different `REACT_APP_FILEUPLOAD_ALLOWED_EXTENSIONS` lists (dev vs. prod)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#74]
I saw that these two lists differ. I am creating this issue in case it was not intentional (i.e. in case person that edited one meant to keep both files in sync).

`client-env-dev`:

https://github.com/microbiomedata/nmdc-edge/blob/277544152f80674623f1d252f63fec5ce0011908/installation/client-env-dev#L20

`client-env-prod`:

https://github.com/microbiomedata/nmdc-edge/blob/277544152f80674623f1d252f63fec5ce0011908/installation/client-env-prod#L20

Here's a diff (after replacing the `|` characters with newlines):

```diff
diff --git a/tmp/dev.txt b/tmp/prod.txt
index e99647c..5429181 100644
--- a/tmp/dev.txt      
+++ b/tmp/prod.txt      
@@ -4,12 +4,22 @@ fq
 fa
 fasta
 fna
+faa
 contigs
 fastq.gz
 fq.gz
 fa.gz
 fasta.gz
 contigs.gz
+fna.gz
+fa.bz2
+fasta.bz2
+contigs.bz2
+fna.bz2
+fa.xz
+fasta.xz
+contigs.xz
+fna.xz
 gbk
 gff
 genbank
@@ -20,4 +30,7 @@ bed
 config
 tsv
 csv
-raw
\ No newline at end of file
+raw
+d
+bam
+sam
\ No newline at end of file

```

**Comment by yxu-lanl** [comment]
Done.
