### ISSUE TITLE
'My Projects' hidden columns for Node v18

### ISSUE THREAD

**Issue by yxu-lanl** [microbiomedata/nmdc-edge#76]
ProjectTable columns' hidden prop doesn't work for Node v18.

**Comment by yxu-lanl** [comment]
https://edge-dev.microbiomedata.org/user/projectlist
![Screenshot 2023-12-11 at 12 15 17 PM](https://github.com/microbiomedata/nmdc-edge/assets/38266469/6600bb1b-ba3b-4fa6-af5b-040292ac3a76)

**Comment by eecavanna** [comment]
Hi @yxu-lanl, here's another symptom you may want to check for when testing Node v20.

**Comment by yxu-lanl** [comment]
I tested that too. No issue anymore.

**Comment by eecavanna** [comment]
OK, thanks. In that case, I'll close this issue since we are jumping straight to Node v20 and this issue was about behavior with Node v18, specifically.
