### ISSUE TITLE
Possible bug: `sendMail.js` uses username as `api_key` and password as `domain`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-edge#89]
https://github.com/microbiomedata/nmdc-edge/blob/f93fc975e0ada1eec1c33a665af3dcd9dba98e59/webapp/server/util/sendMail.js#L24-L28

**Comment by yxu-lanl** [comment]
The original design is only for gmail SMTP server. When SMTP service failed, we did a quick test with the mailgun. Yes. We need to rewrite this part.
