### ISSUE TITLE
sync NMDC-EDGE with NMDC annotation and binning workflows

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-edge#9]
There have been updates to both annotation and binning workflows, this includes new file outputs and inputs, new docker containers, and new database versions.

annotation should use https://github.com/microbiomedata/mg_annotation/releases/tag/v1.0.4
binning should use https://github.com/microbiomedata/metaMAGs

cc @patrickchain

**Comment by ssarrafan** [comment]
@aclum @mflynn-lanl any update on this issue? It doesn't appear to be active?  Can we add this to the backlog?

**Comment by mflynn-lanl** [comment]
I am still working on this. I've gotten NMDC annotation to work on NMDC-EDGE. I'm verifying that all of the files needed for the website are there

**Comment by ssarrafan** [comment]
Moving to next sprint per last comment

**Comment by aclum** [comment]
@mflynn-lanl  how are we doing on this one?

**Comment by ssarrafan** [comment]
Moving to next sprint per @mflynn-lanl

**Comment by mflynn-lanl** [comment]
Updated WDL files to match NMDC and updated Cromwell config file to match changes to the WDL files.  I'm testing the workflows now using our nmdc-edge test instance

**Comment by mflynn-lanl** [comment]
I have tested annotation and incorporated the WDLs into NMDC-EDGE. I'm still working on binning.

**Comment by aclum** [comment]
actively being worked on based on comments in the workflow slack channel, moving to the next sprint @mflynn-lanl

**Comment by mflynn-lanl** [comment]
updated mbin_nmdc.wdl in nmdc-edge. however, this will require changes to the nmdc version. There are outputs required by the website that are not currently in the output section of mbin_nmdc.wdl. I posted a question to slack to see if there are any objections, if not I'll push the changes to the NMDC metaMAGs repo

**Comment by mflynn-lanl** [comment]
The workflows have been synced. Yan updated the React GUI. I am waiting for the end of a DST for our local cluster to test the changes before we deploy to production

**Comment by ssarrafan** [comment]
@mflynn-lanl what's the status of this?  Have the changes been tested?  Can this issue be closed? 
FYI @aclum

**Comment by ssarrafan** [comment]
@mflynn-lanl said this should be moved to the next sprint. Moving it.

**Comment by ssarrafan** [comment]
@mflynn-lanl is this still in review?

**Comment by mflynn-lanl** [comment]
yes, I haven't had a chance to push the changes to production.
________________________________
From: ssarrafan ***@***.***>
Sent: Friday, January 5, 2024 4:30 PM
To: microbiomedata/nmdc-edge ***@***.***>
Cc: Flynn, Mark C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/nmdc-edge] sync NMDC-EDGE with NMDC annotation and binning workflows (Issue #9)


@mflynn-lanl<https://urldefense.com/v3/__https://github.com/mflynn-lanl__;!!Bt8fGhp8LhKGRg!ECOWH3_ZErnEwHlRJzDESLoGmh8T5fSoqx3f4HErtpNYqWApqEvKAAFkKFSP_GaaDVbKJ5djAEujrv-CVyNKJvSX$> is this still in review?

**Comment by emileyfadrosh** [comment]
@mflynn-lanl @aclum could we get an update on this? It would be great to have this completed this sprint and definitely before the GSP. Thanks!

**Comment by ssarrafan** [comment]
@emileyfadrosh Mark F said he's " almost done. I've done all of the WDLs except for Readbased Analysis". Adding to the current sprint for the last piece.

**Comment by ssarrafan** [comment]
@mflynn-lanl can this be closed?

**Comment by ssarrafan** [comment]
@mflynn-lanl what''s the status of this issue? This was on the GSP/ECR board.
@shreddd

**Comment by mflynn-lanl** [comment]
I'm testing the last changes right now. I will close it either today or tomorrow
Mark
________________________________
From: ssarrafan ***@***.***>
Sent: Tuesday, April 9, 2024 4:03 PM
To: microbiomedata/nmdc-edge ***@***.***>
Cc: Flynn, Mark C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/nmdc-edge] sync NMDC-EDGE with NMDC annotation and binning workflows (Issue #9)


@mflynn-lanl<https://urldefense.com/v3/__https://github.com/mflynn-lanl__;!!Bt8fGhp8LhKGRg!FIHjXphkF-8bYUUhF7WCStBiNg4QHRPpHdd0ypkJOVyN7NGsN2CgWaFuwAkwtNnv1TuKdy3ifL7jjDufP0f0TlOq$> what''s the status of this issue? This was on the GSP/ECR board.
@shreddd<https://urldefense.com/v3/__https://github.com/shreddd__;!!Bt8fGhp8LhKGRg!FIHjXphkF-8bYUUhF7WCStBiNg4QHRPpHdd0ypkJOVyN7NGsN2CgWaFuwAkwtNnv1TuKdy3ifL7jjDufP9B3lzna$>

**Comment by ssarrafan** [comment]
@mflynn-lanl this is still open?  Can it be closed today please?

**Comment by ssarrafan** [comment]
@mflynn-lanl is waiting for test data from @aclum to do final testing
moving to next sprint

**Comment by ssarrafan** [comment]
@aclum @mflynn-lanl I'm removing this from the sprint with a backlog label as it hasn't been updated in 2 weeks.

**Comment by mflynn-lanl** [comment]
Sorry Set! Can you add it back to the sprint? I'm still working on it. I honestly thought I'd be done 2 weeks ago
________________________________
From: ssarrafan ***@***.***>
Sent: Monday, May 6, 2024 12:01 PM
To: microbiomedata/nmdc-edge ***@***.***>
Cc: Flynn, Mark C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/nmdc-edge] sync NMDC-EDGE with NMDC annotation and binning workflows (Issue #9)


@aclum<https://urldefense.com/v3/__https://github.com/aclum__;!!Bt8fGhp8LhKGRg!HW6R6SWL3agKDXUDYmyPJedAes8Q8XOMX_9h9dAbmo3-vf3lkUmmesIE6NZEPkQEF6J5JCjZ81UkOthgG9mNSKsV$> @mflynn-lanl<https://urldefense.com/v3/__https://github.com/mflynn-lanl__;!!Bt8fGhp8LhKGRg!HW6R6SWL3agKDXUDYmyPJedAes8Q8XOMX_9h9dAbmo3-vf3lkUmmesIE6NZEPkQEF6J5JCjZ81UkOthgG4PagslG$> I'm removing this from the sprint with a backlog label as it hasn't been updated in 2 weeks.
