### ISSUE TITLE
Lock-down options for the Metagenomics pipeline

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/nmdc-edge#94]
**Is your feature request related to a problem? Please describe.**
We would like to restrict the Metagenomics pipeline so that all options have been removed. Each project will run all of the workflows in the pipeline and all will use the same options

**Describe the solution you'd like**
Modify metagenome_pipeline_wdl.tmpl so that it runs all workflows. The only options users will have is the input files 

**Additional context**
The website will need to be modified to remove the option for users to select which workflows they'd like to run

**Comment by mflynn-lanl** [comment]
Workflows are failing for the metagenomics pipeline if they un-select any of the Readbased Analysis tools. @yxu-lanl Can you remove the option from the metagenomics pipeline to un-select tools?

**Comment by yxu-lanl** [comment]
Done and deployed. https://github.com/microbiomedata/nmdc-edge/pull/101
